services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: obs-llama-app
    env_file:
      - .env
    working_dir: /app
    volumes:
      - .:/app
      - ${LLAMA_MODELS_HOST_DIR}:/models
    ports:
      - "${APP_PORT:-8000}:${APP_PORT:-8000}"

    # Habilitar GPU
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

    tty: true
